#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun  8 02:40:10 2018

@author: manana
"""

import re

line_template = "ios-regex '{}',"

with open('as-path-access-list-2-old.txt') as f:
    for line in f:
        s = re.search(r'^.*$', line).group()
        print(line_template.format(s))