#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 11 09:28:40 2018

@author: manana
"""

from my_module import print_int


print_int(5)
print_int(7)
print_int(20)
print_int(100)

print(__name__)